public class MinhaClasse { // Nota: Nome da classe deve ser o mesmo do arquivo e em maiúsculo.
    // Nota 02: o código Java é case-sensitive, ou seja, diferencia maiúsculas de minúsculas.
    // Toda aplicação Java deve ter um método main.

    //o método main é o ponto de entrada do programa, é aconselhado que ele esteja dentro de uma classe apenas uma vez. Fazendo com que essa classe escolhida seja chamada de 'Classe Executável'.
    
    public static void main(String[] args) {
        System.out.println("Olá, Mundo!");

    }
    
}